exclude: /(vendor|dist)/
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-merge-conflict
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: name-tests-test
        args: ['--pytest-test-first']
        exclude: ^tests/helpers/
      - id: trailing-whitespace
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.8.3
    hooks:
      - id: commitizen
        additional_dependencies: ['cz-nhm']
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.7
    hooks:
      - id: ruff
        args: [ '--fix', '--select', 'I', '--select', 'F401', '--fix-only' ]
      - id: ruff-format
  - repo: https://github.com/PyCQA/docformatter
    rev: v1.7.7
    hooks:
      - id: docformatter
        args: [ '-i', '--config', './pyproject.toml' ]
        additional_dependencies: ['tomli']
