language: python
dist: bionic
python:
  - 3.8
before_install:
  - sudo apt-get update
  - sudo apt-get -y install libffi-dev
  - sudo apt-get -y install libturbojpeg0-dev libjpeg-dev
  - sudo apt-get -y install libpcre3 libpcre3-dev
  - sudo apt-get -y install libcurl4-openssl-dev libssl-dev
  - pip install -U pip
  - pip install coveralls coverage
install:
  - pip install .
  - pip install ".[test]"
script: coverage run -m pytest
after_success: coveralls
