name: Tests

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Install OS dependencies
        run: sudo apt-get -y install libffi-dev libturbojpeg0-dev libjpeg-dev libpcre3 libpcre3-dev libcurl4-openssl-dev libssl-dev build-essential libmagickwand-dev

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: x64

      - name: Update pip
        run: pip install -U pip

      - name: Install Python test package dependencies
        run: pip install pytest-cov coveralls

      - name: Install IIIF Image Server
        run: pip install ".[test]"

      - name: Run tests
        run: pytest --cov=iiif

      - name: Run coveralls
        run: coveralls --service=github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
